import path from "node:path";
import type {
  TierkitAdapter,
  AdapterExportInput,
  ExportFile,
  ExportResult,
  ExportWarning,
  LoadedPlugin,
} from "@tierkit/core";
import { listGrantedPermissions, listHighRiskGranted } from "@tierkit/core";
import { renderPermissionContract } from "./permissionContract.js";
import {
  renderPluginCommands,
  renderPluginModes,
  renderPluginRules,
} from "./renderClineFiles.js";

const HEADER =
  "<!-- Generated by Tierkit. Do not edit by hand — edit the source plugin and re-export. -->";

export class ClineAdapter implements TierkitAdapter {
  readonly target = "cline" as const;
  readonly name = "Cline";
  readonly description =
    "Exports Tierkit plugins as .clinerules/ markdown files plus .cline/mcp for manual MCP setup.";

  async export(input: AdapterExportInput): Promise<ExportResult> {
    const files: ExportFile[] = [];
    const warnings: ExportWarning[] = [];

    for (const plugin of input.plugins) {
      this.exportPermissionContract(plugin, files);
      this.absorb(renderPluginRules(plugin), files, warnings);
      this.absorb(renderPluginModes(plugin), files, warnings);
      this.absorb(renderPluginCommands(plugin), files, warnings);
      this.exportMcpFor(plugin, files, warnings);
    }

    files.push({
      path: ".clinerules/TIERKIT.md",
      contents: renderClineRulesReadme(input.plugins),
    });
    files.push({
      path: ".cline/TIERKIT.md",
      contents: renderClineMcpReadme(input.plugins),
    });

    return { target: this.target, files, warnings };
  }

  private exportPermissionContract(plugin: LoadedPlugin, files: ExportFile[]): void {
    files.push({
      pluginId: plugin.manifest.id,
      path: `.clinerules/00-${plugin.manifest.id}-permission.md`,
      contents: `${HEADER}\n\n${renderPermissionContract(plugin.manifest)}`,
    });
  }

  private absorb(
    result: { files: { pluginId: string; path: string; contents: string }[]; warnings: { pluginId: string; message: string }[] },
    files: ExportFile[],
    warnings: ExportWarning[],
  ): void {
    for (const f of result.files) files.push(f);
    for (const w of result.warnings) warnings.push(w);
  }

  private exportMcpFor(
    plugin: LoadedPlugin,
    files: ExportFile[],
    warnings: ExportWarning[],
  ): void {
    const mcpFile = plugin.manifest.components.mcpServers;
    if (!mcpFile) return;
    const body = plugin.files.get(mcpFile);
    if (body === undefined) {
      warnings.push({
        pluginId: plugin.manifest.id,
        message: `mcpServers references missing file "${mcpFile}" — skipped`,
      });
      return;
    }
    files.push({
      pluginId: plugin.manifest.id,
      path: path.posix.join(".cline", "mcp", `${plugin.manifest.id}.json`),
      contents: body,
    });
    warnings.push({
      pluginId: plugin.manifest.id,
      message:
        "MCP server config exported. Cline will NOT auto-register — review and add to your Cline MCP settings manually.",
    });
    if (!plugin.manifest.permissions.registerMcp) {
      warnings.push({
        pluginId: plugin.manifest.id,
        message:
          "Plugin declares mcpServers but does not request the `registerMcp` permission. Export emitted for reference only; do not configure.",
      });
    }
  }
}

function renderClineRulesReadme(plugins: LoadedPlugin[]): string {
  const lines: string[] = [
    HEADER,
    "",
    "# Tierkit → Cline export",
    "",
    "Cline loads everything in this directory automatically as context. Files are processed in alphabetical order, which is why each filename is prefixed with a numeric ordering key:",
    "",
    "| Prefix | Purpose |",
    "|---|---|",
    "| `00-` | Permission contract — what each plugin may and may not do. Loaded first so the rest is interpreted in its light. |",
    "| `10-` | Original plugin rules. |",
    "| `20-` | Modes translated to persona rules (Cline has no first-class custom modes). |",
    "| `30-` | Commands translated to slash-command-style rules (Cline has no first-class slash commands). |",
    "",
    "## Installed plugins",
    "",
  ];
  if (plugins.length === 0) {
    lines.push("_(no plugins installed)_", "");
  } else {
    for (const p of plugins) {
      const m = p.manifest;
      const perms = listGrantedPermissions(m.permissions);
      const highRisk = listHighRiskGranted(m.permissions);
      lines.push(`### ${m.name} \`${m.id}@${m.version}\``);
      lines.push("");
      lines.push(m.description);
      lines.push("");
      lines.push(`- **freedom**: ${m.freedom.level}`);
      lines.push(
        `- **permissions**: ${perms.length === 0 ? "(none)" : perms.map((p) => `\`${p}\``).join(", ")}`,
      );
      if (highRisk.length > 0) {
        lines.push(
          `- **high-risk granted**: ${highRisk.map((p) => `\`${p}\``).join(", ")} — review before use`,
        );
      }
      lines.push("");
    }
  }
  lines.push(
    "## Older Cline versions",
    "",
    "Older Cline releases expected `.clinerules` as a single file rather than a directory. If you are on such a release, concatenate the files in this directory (in alphabetical order) into a single `.clinerules` file.",
    "",
    "## Re-export",
    "",
    "After updating a plugin source, re-run `tierkit export cline` to regenerate this directory.",
    "",
  );
  return lines.join("\n");
}

function renderClineMcpReadme(plugins: LoadedPlugin[]): string {
  const withMcp = plugins.filter((p) => p.manifest.components.mcpServers);
  const lines: string[] = [
    HEADER,
    "",
    "# Tierkit → Cline MCP staging",
    "",
    "Tierkit never auto-registers MCP servers. The files under `mcp/` are reference configurations exported from each plugin. To use one, open Cline's MCP settings and add the server manually.",
    "",
  ];
  if (withMcp.length === 0) {
    lines.push("_(no plugins declared MCP servers in this export)_", "");
  } else {
    lines.push("## Plugins that declared MCP servers", "");
    for (const p of withMcp) {
      lines.push(`- \`${p.manifest.id}\` → see \`mcp/${p.manifest.id}.json\``);
      if (!p.manifest.permissions.registerMcp) {
        lines.push(
          `  - ⚠️ This plugin did **not** request the \`registerMcp\` permission. Treat the config as reference only.`,
        );
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}
