import type { PermissionFlags, PluginManifest } from "@tierkit/core";

/**
 * Cline has no first-class permission/group system. We translate the plugin's
 * declared permissions into natural-language rules that the agent is asked to
 * follow. The contract is always emitted as the highest-priority file in
 * `.clinerules/` so it loads first.
 *
 * Stance: adapters never *upgrade* permissions. A plugin that did not declare
 * `runCommands` produces an explicit "do not run shell commands" rule.
 */
export function renderPermissionContract(manifest: PluginManifest): string {
  const p: PermissionFlags = manifest.permissions;
  const mustNot: string[] = [];
  const may: string[] = [];

  if (p.readFiles) may.push("Read files in the workspace.");
  else mustNot.push("Read files outside of what the user explicitly shares.");

  if (p.editFiles) may.push("Edit files in the workspace.");
  else mustNot.push("Edit, create, or delete files in the workspace.");

  if (p.runCommands) {
    may.push("Run shell commands — always surface what will run and pause for approval first.");
  } else {
    mustNot.push("Run shell commands of any kind. Even read-only commands are out of scope for this plugin.");
  }

  if (p.installDependencies) {
    may.push("Install dependencies — explicit approval required for every install.");
  } else {
    mustNot.push("Install, update, or remove dependencies.");
  }

  if (p.modifyAgentSettings) {
    may.push("Modify Cline / agent settings — explicit approval required.");
  } else {
    mustNot.push("Modify Cline settings, custom instructions, or MCP configuration.");
  }

  if (p.registerMcp) {
    may.push(
      "Suggest registering an MCP server — but never silently auto-register; always ask the user to add it in Cline MCP settings.",
    );
  } else {
    mustNot.push("Register MCP servers. If MCP work appears necessary, stop and ask the user.");
  }

  if (p.accessSecrets) {
    may.push("Read secrets only when the task demonstrably needs them. Never send secrets to a remote model without redaction.");
  } else {
    mustNot.push("Access secrets, credentials, environment variables holding tokens, or `.env`-style files.");
  }

  if (p.useNetwork) {
    may.push("Make network requests when the task requires them.");
  } else {
    mustNot.push("Make outbound network requests.");
  }

  if (p.usePublicCloudModel) {
    may.push(
      "Use a public-cloud model — only in review-only mode and only after the user explicitly approves the escalation.",
    );
  } else {
    mustNot.push("Use public-cloud models. This plugin operates on local-device (and optionally private-remote) models only.");
  }

  if (p.usePrivateRemoteModel) {
    may.push("Use a private-remote model when the task exceeds local-device capacity.");
  }

  const lines: string[] = [
    `# Permission contract — ${manifest.name} (\`${manifest.id}\`)`,
    "",
    "_This file is auto-generated by Tierkit from the plugin's `permissions` block. Do not edit directly._",
    "",
    `Plugin **${manifest.id}** declared the following permission contract. The agent must follow it strictly while this plugin's context is loaded.`,
    "",
    "## You MAY",
    "",
  ];
  if (may.length === 0) {
    lines.push("_(nothing — this plugin is read-only-passive)_", "");
  } else {
    for (const item of may) lines.push(`- ${item}`);
    lines.push("");
  }

  lines.push("## You MUST NOT", "");
  if (mustNot.length === 0) {
    lines.push("_(no explicit prohibitions)_", "");
  } else {
    for (const item of mustNot) lines.push(`- ${item}`);
    lines.push("");
  }

  lines.push(
    "## Escalation",
    "",
    "- Public-cloud model output is **review-only** — it may suggest changes, but a local or private-remote model applies them after human review.",
    "- Before sending any context to a remote tier (private-remote or public-cloud), redact secrets, production URLs, and customer data.",
    "",
  );

  return lines.join("\n");
}
