import path from "node:path";
import type { LoadedPlugin } from "@tierkit/core";

/**
 * Cline does not have first-class commands or modes the way Roo does. Everything we
 * emit lands inside `.clinerules/` as markdown files. Cline loads them alphabetically,
 * so we prefix each filename with a fixed order key:
 *
 *   00-<pluginId>-permission.md  → permission contract (always first)
 *   10-<pluginId>-rule-<name>.md → original plugin rules
 *   20-<pluginId>-mode-<id>.md   → modes translated to persona rules
 *   30-<pluginId>-command-<id>.md → commands translated to slash-command-style rules
 */

const HEADER =
  "<!-- Generated by Tierkit. Do not edit by hand — edit the source plugin and re-export. -->";

export interface RenderedFile {
  pluginId: string;
  path: string;
  contents: string;
}

export interface RenderWarning {
  pluginId: string;
  message: string;
}

export interface RenderResult {
  files: RenderedFile[];
  warnings: RenderWarning[];
}

export function renderPluginRules(plugin: LoadedPlugin): RenderResult {
  const id = plugin.manifest.id;
  const files: RenderedFile[] = [];
  const warnings: RenderWarning[] = [];

  for (const rel of plugin.manifest.components.rules) {
    const body = plugin.files.get(rel);
    if (body === undefined) {
      warnings.push({ pluginId: id, message: `rule references missing file "${rel}" — skipped` });
      continue;
    }
    const slug = slugify(path.basename(rel, path.extname(rel)));
    files.push({
      pluginId: id,
      path: `.clinerules/10-${id}-rule-${slug}.md`,
      contents: `${HEADER}\n\n${body.trim()}\n`,
    });
  }

  return { files, warnings };
}

export function renderPluginModes(plugin: LoadedPlugin): RenderResult {
  const id = plugin.manifest.id;
  const files: RenderedFile[] = [];
  const warnings: RenderWarning[] = [];

  for (const mode of plugin.manifest.components.modes) {
    const body = plugin.files.get(mode.file);
    if (body === undefined) {
      warnings.push({
        pluginId: id,
        message: `mode "${mode.id}" references missing file "${mode.file}" — skipped`,
      });
      continue;
    }
    const lines = [
      HEADER,
      "",
      `# Persona: ${mode.name}`,
      "",
      `_(from plugin \`${id}\`, mode id \`${mode.id}\`, role \`${mode.role}\`. Cline has no first-class custom modes — when the user asks the agent to adopt this persona, follow the body below.)_`,
      "",
      `**Declared tools:** ${mode.tools.length === 0 ? "(none)" : mode.tools.map((t) => `\`${t}\``).join(", ")}. These are *intentions*, not capabilities — the permission contract for this plugin still wins.`,
      "",
      body.trim(),
      "",
    ];
    files.push({
      pluginId: id,
      path: `.clinerules/20-${id}-mode-${slugify(mode.id)}.md`,
      contents: lines.join("\n"),
    });
  }

  return { files, warnings };
}

export function renderPluginCommands(plugin: LoadedPlugin): RenderResult {
  const id = plugin.manifest.id;
  const files: RenderedFile[] = [];
  const warnings: RenderWarning[] = [];

  for (const cmd of plugin.manifest.components.commands) {
    const body = plugin.files.get(cmd.file);
    if (body === undefined) {
      warnings.push({
        pluginId: id,
        message: `command "${cmd.name}" references missing file "${cmd.file}" — skipped`,
      });
      continue;
    }
    const lines = [
      HEADER,
      "",
      `# Command: /${cmd.name}`,
      "",
      `_(from plugin \`${id}\`, category \`${cmd.category}\`. Cline does not register slash commands automatically — when the user types \`/${cmd.name}\` or asks for a "${cmd.name}", follow the workflow below.)_`,
      "",
      `**Description:** ${cmd.description}`,
      "",
      body.trim(),
      "",
    ];
    files.push({
      pluginId: id,
      path: `.clinerules/30-${id}-command-${slugify(cmd.name)}.md`,
      contents: lines.join("\n"),
    });
  }

  return { files, warnings };
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}
