import path from "node:path";
import type {
  TierkitAdapter,
  AdapterExportInput,
  ExportFile,
  ExportResult,
  ExportWarning,
  LoadedPlugin,
} from "@tierkit/core";
import { listGrantedPermissions, listHighRiskGranted } from "@tierkit/core";
import { renderModes } from "./renderModes.js";

const GENERATED_HEADER =
  "<!-- Generated by Tierkit. Do not edit by hand — edit the source plugin and re-export. -->";

export class RooAdapter implements TierkitAdapter {
  readonly target = "roo" as const;
  readonly name = "Roo / Zoo Code";
  readonly description =
    "Exports Tierkit plugins as .roomodes plus .roo/commands, .roo/rules, and .roo/mcp.";

  async export(input: AdapterExportInput): Promise<ExportResult> {
    const files: ExportFile[] = [];
    const warnings: ExportWarning[] = [];

    const modesResult = renderModes(input.plugins);
    if (modesResult.file.customModes.length > 0) {
      files.push({
        path: ".roomodes",
        contents: JSON.stringify(modesResult.file, null, 2) + "\n",
      });
    }
    for (const w of modesResult.warnings) warnings.push(w);

    for (const plugin of input.plugins) {
      this.exportCommandsFor(plugin, files, warnings);
      this.exportRulesFor(plugin, files, warnings);
      this.exportMcpFor(plugin, files, warnings);
    }

    files.push({
      path: ".roo/TIERKIT.md",
      contents: renderExportReadme(input.plugins),
    });

    return { target: this.target, files, warnings };
  }

  private exportCommandsFor(
    plugin: LoadedPlugin,
    files: ExportFile[],
    warnings: ExportWarning[],
  ): void {
    for (const cmd of plugin.manifest.components.commands) {
      const body = plugin.files.get(cmd.file);
      if (body === undefined) {
        warnings.push({
          pluginId: plugin.manifest.id,
          message: `command "${cmd.name}" references missing file "${cmd.file}" — skipped`,
        });
        continue;
      }
      const lines = [
        "---",
        `name: ${cmd.name}`,
        `description: ${jsonish(cmd.description)}`,
        `category: ${cmd.category}`,
        `plugin: ${plugin.manifest.id}`,
        "---",
        "",
        GENERATED_HEADER,
        "",
        body.trim(),
        "",
      ];
      files.push({
        pluginId: plugin.manifest.id,
        path: path.posix.join(".roo", "commands", `${plugin.manifest.id}-${cmd.name}.md`),
        contents: lines.join("\n"),
      });
    }
  }

  private exportRulesFor(
    plugin: LoadedPlugin,
    files: ExportFile[],
    warnings: ExportWarning[],
  ): void {
    for (const rel of plugin.manifest.components.rules) {
      const body = plugin.files.get(rel);
      if (body === undefined) {
        warnings.push({
          pluginId: plugin.manifest.id,
          message: `rule references missing file "${rel}" — skipped`,
        });
        continue;
      }
      files.push({
        pluginId: plugin.manifest.id,
        path: path.posix.join(".roo", "rules", plugin.manifest.id, path.basename(rel)),
        contents: `${GENERATED_HEADER}\n\n${body.trim()}\n`,
      });
    }
  }

  private exportMcpFor(
    plugin: LoadedPlugin,
    files: ExportFile[],
    warnings: ExportWarning[],
  ): void {
    const mcpFile = plugin.manifest.components.mcpServers;
    if (!mcpFile) return;
    const body = plugin.files.get(mcpFile);
    if (body === undefined) {
      warnings.push({
        pluginId: plugin.manifest.id,
        message: `mcpServers references missing file "${mcpFile}" — skipped`,
      });
      return;
    }
    files.push({
      pluginId: plugin.manifest.id,
      path: path.posix.join(".roo", "mcp", `${plugin.manifest.id}.json`),
      contents: body,
    });
    warnings.push({
      pluginId: plugin.manifest.id,
      message:
        "MCP server config exported. Roo will NOT auto-register — review and add to your Roo MCP settings manually.",
    });
  }
}

function renderExportReadme(plugins: LoadedPlugin[]): string {
  const lines: string[] = [
    "# Tierkit → Roo / Zoo Code export",
    "",
    GENERATED_HEADER,
    "",
    "This directory was produced by `tierkit export roo`.",
    "",
    "## Layout",
    "",
    "- `../.roomodes` — Roo custom modes for every Tierkit mode in the installed plugins.",
    "- `commands/<plugin-id>-<command>.md` — slash command bodies. Roo does not auto-register these as slash commands; paste into chat or attach as context when you need them.",
    "- `rules/<plugin-id>/<rule>.md` — Roo loads `.roo/rules` automatically into every conversation.",
    "- `mcp/<plugin-id>.json` — MCP server configuration. **Roo will not auto-register MCP servers.** Inspect and add to your Roo MCP settings if you trust the source.",
    "",
    "## Installed plugins",
    "",
  ];
  if (plugins.length === 0) {
    lines.push("_(no plugins installed)_", "");
  } else {
    for (const p of plugins) {
      const m = p.manifest;
      const perms = listGrantedPermissions(m.permissions);
      const highRisk = listHighRiskGranted(m.permissions);
      lines.push(`### ${m.name} \`${m.id}@${m.version}\``);
      lines.push("");
      lines.push(m.description);
      lines.push("");
      lines.push(`- **freedom**: ${m.freedom.level}`);
      lines.push(`- **permissions**: ${perms.length === 0 ? "(none)" : perms.map((p) => `\`${p}\``).join(", ")}`);
      if (highRisk.length > 0) {
        lines.push(`- **high-risk granted**: ${highRisk.map((p) => `\`${p}\``).join(", ")} — review before use`);
      }
      lines.push("");
    }
  }
  lines.push(
    "## Re-export",
    "",
    "After updating a plugin source, re-run `tierkit export roo` to regenerate this directory.",
    "",
  );
  return lines.join("\n");
}

function jsonish(s: string): string {
  if (/[":#\n]/.test(s)) return JSON.stringify(s);
  return s;
}
