import { describe, it, expect } from "vitest";
import { parse as yamlParse } from "yaml";
import { renderContinueConfig } from "../src/renderContinueConfig.js";
import { makeConfig } from "./fixtures.js";

describe("renderContinueConfig", () => {
  it("emits a header comment + valid YAML with empty models when no tierkit config", () => {
    const r = renderContinueConfig({});
    expect(r.yaml).toMatch(/^# Generated by Tierkit/);
    expect(r.yaml).toContain("TODO: no model profiles");
    const parsed = yamlParse(r.yaml);
    expect(parsed.name).toBe("tierkit-export");
    expect(parsed.schema).toBe("v1");
    expect(parsed.models).toEqual([]);
  });

  it("translates Tierkit model profiles into Continue model entries", () => {
    const r = renderContinueConfig({ config: makeConfig() });
    const parsed = yamlParse(r.yaml);
    expect(parsed.models).toHaveLength(3);

    const local = parsed.models.find((m: { name: string }) => m.name === "localFast");
    expect(local.provider).toBe("ollama");
    expect(local.model).toBe("qwen2.5-coder:7b");
    expect(local.apiBase).toBe("http://localhost:11434");

    const priv = parsed.models.find((m: { name: string }) => m.name === "privateRemoteStrong");
    expect(priv.provider).toBe("openai");
    expect(priv.apiKey).toBe("${{ secrets.TIERKIT_PRIVATE_LLM_KEY }}");
  });

  it("forces public-cloud profiles to chat-only roles", () => {
    const r = renderContinueConfig({ config: makeConfig() });
    const parsed = yamlParse(r.yaml);
    const cloud = parsed.models.find((m: { name: string }) => m.name === "publicCloudPremium");
    expect(cloud.roles).toEqual(["chat"]);
  });

  it("emits no autocomplete role for private-remote profiles", () => {
    const r = renderContinueConfig({ config: makeConfig() });
    const parsed = yamlParse(r.yaml);
    const priv = parsed.models.find((m: { name: string }) => m.name === "privateRemoteStrong");
    expect(priv.roles).not.toContain("autocomplete");
  });
});
