import { describe, it, expect, afterEach } from "vitest";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Writable } from "node:stream";
import { parse as yamlParse } from "yaml";
import { buildCli } from "../src/cli.js";
import type { CliContext } from "../src/context/CliContext.js";

const TEST_DIR = path.dirname(fileURLToPath(import.meta.url));
const SUPERPOWERS_FREE_DIR = path.resolve(
  TEST_DIR,
  "../../plugin-superpowers/plugins/superpowers-free",
);

class StringSink extends Writable {
  chunks: Buffer[] = [];
  override _write(chunk: Buffer, _enc: unknown, cb: (err?: Error | null) => void): void {
    this.chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    cb();
  }
  text(): string {
    return Buffer.concat(this.chunks).toString("utf8");
  }
}

function makeContext(cwd: string): { context: CliContext; stdout: StringSink; stderr: StringSink } {
  const stdout = new StringSink();
  const stderr = new StringSink();
  return {
    context: {
      stdin: process.stdin,
      stdout,
      stderr,
      env: process.env as Record<string, string>,
      colorDepth: 1,
      cwd,
    },
    stdout,
    stderr,
  };
}

// v0.19: `tierkit export continue` command disabled.
describe.skip("CLI e2e: export continue (superpowers-free)", () => {
  let projectRoot: string;
  afterEach(async () => {
    if (projectRoot) await fs.rm(projectRoot, { recursive: true, force: true });
  });

  it("produces config.yaml + rules/ + prompts/ + TIERKIT.md", async () => {
    projectRoot = await fs.mkdtemp(path.join(os.tmpdir(), "tierkit-e2e-continue-"));
    const cli = buildCli();

    expect(await cli.run(["init"], makeContext(projectRoot).context)).toBe(0);
    expect(
      await cli.run(
        ["plugin", "install", SUPERPOWERS_FREE_DIR],
        makeContext(projectRoot).context,
      ),
    ).toBe(0);

    const ctx = makeContext(projectRoot);
    expect(await cli.run(["export", "continue"], ctx.context)).toBe(0);
    expect(ctx.stdout.text()).toContain('target "continue"');

    const continueDir = path.join(projectRoot, ".continue");
    const configText = await fs.readFile(path.join(continueDir, "config.yaml"), "utf8");
    expect(configText).toMatch(/^# Generated by Tierkit/);
    const config = yamlParse(configText);
    expect(config.name).toBe("tierkit-export");

    const ruleEntries = (await fs.readdir(path.join(continueDir, "rules"))).sort();
    expect(ruleEntries).toContain("00-superpowers-free-permission.md");
    expect(ruleEntries).toContain("10-superpowers-free-rule-local-first.md");
    expect(ruleEntries).toContain("20-superpowers-free-mode-free-coder.md");
    expect(ruleEntries).toContain("20-superpowers-free-mode-brainstormer.md");
    expect(ruleEntries).toContain("20-superpowers-free-mode-reviewer.md");

    const promptEntries = (await fs.readdir(path.join(continueDir, "prompts"))).sort();
    expect(promptEntries).toEqual([
      "superpowers-free-brainstorm.prompt",
      "superpowers-free-debug.prompt",
      "superpowers-free-escalate.prompt",
      "superpowers-free-review.prompt",
    ]);

    const brainstorm = await fs.readFile(
      path.join(continueDir, "prompts/superpowers-free-brainstorm.prompt"),
      "utf8",
    );
    expect(brainstorm).toMatch(/^---\nname: superpowers-free-brainstorm/);

    const readme = await fs.readFile(path.join(continueDir, "TIERKIT.md"), "utf8");
    expect(readme).toContain("Tierkit → Continue export");
  });

  it("populates config.yaml::models when tierkit.config.json has modelProfiles", async () => {
    projectRoot = await fs.mkdtemp(path.join(os.tmpdir(), "tierkit-e2e-continue-models-"));
    const cli = buildCli();

    expect(await cli.run(["init"], makeContext(projectRoot).context)).toBe(0);
    // Overwrite the freshly-created config with one that has model profiles.
    const cfgPath = path.join(projectRoot, "tierkit.config.json");
    await fs.writeFile(
      cfgPath,
      JSON.stringify(
        {
          version: "0.1",
          defaultTarget: "continue",
          modelProfiles: {
            localFast: {
              kind: "local-device",
              provider: "ollama",
              baseUrl: "http://localhost:11434",
              model: "qwen2.5-coder:7b",
              roles: ["simple-coder"],
            },
          },
        },
        null,
        2,
      ),
    );
    expect(
      await cli.run(
        ["plugin", "install", SUPERPOWERS_FREE_DIR],
        makeContext(projectRoot).context,
      ),
    ).toBe(0);
    expect(await cli.run(["export", "continue"], makeContext(projectRoot).context)).toBe(0);

    const cfg = yamlParse(
      await fs.readFile(path.join(projectRoot, ".continue/config.yaml"), "utf8"),
    );
    expect(cfg.models).toHaveLength(1);
    expect(cfg.models[0].name).toBe("localFast");
    expect(cfg.models[0].provider).toBe("ollama");
  });
});
