import path from "node:path";
import type {
  TierkitAdapter,
  AdapterExportInput,
  ExportFile,
  ExportResult,
  ExportWarning,
  LoadedPlugin,
} from "@tierkit/core";
import { listGrantedPermissions, listHighRiskGranted } from "@tierkit/core";
import { renderContinueConfig } from "./renderContinueConfig.js";
import {
  renderPermissionContract,
  renderPluginRules,
  renderPluginModes,
  renderPluginPrompts,
} from "./renderContinueFiles.js";

const HEADER =
  "<!-- Generated by Tierkit. Do not edit by hand — edit the source plugin and re-export. -->";

export class ContinueAdapter implements TierkitAdapter {
  readonly target = "continue" as const;
  readonly name = "Continue";
  readonly description =
    "Exports Tierkit plugins as .continue/{config.yaml, rules/, prompts/, mcp/} plus TIERKIT.md staging README.";

  async export(input: AdapterExportInput): Promise<ExportResult> {
    const files: ExportFile[] = [];
    const warnings: ExportWarning[] = [];

    const configResult = renderContinueConfig({ ...(input.config ? { config: input.config } : {}) });
    for (const w of configResult.warnings) warnings.push(w);
    files.push({ path: ".continue/config.yaml", contents: configResult.yaml });

    for (const plugin of input.plugins) {
      files.push(renderPermissionContract(plugin.manifest));
      this.absorb(renderPluginRules(plugin), files, warnings);
      this.absorb(renderPluginModes(plugin), files, warnings);
      this.absorb(renderPluginPrompts(plugin), files, warnings);
      this.exportMcpFor(plugin, files, warnings);
    }

    files.push({
      path: ".continue/TIERKIT.md",
      contents: renderContinueReadme(input.plugins, input.config !== undefined),
    });

    return { target: this.target, files, warnings };
  }

  private absorb(
    result: {
      files: { pluginId: string; path: string; contents: string }[];
      warnings: { pluginId: string; message: string }[];
    },
    files: ExportFile[],
    warnings: ExportWarning[],
  ): void {
    for (const f of result.files) files.push(f);
    for (const w of result.warnings) warnings.push(w);
  }

  private exportMcpFor(
    plugin: LoadedPlugin,
    files: ExportFile[],
    warnings: ExportWarning[],
  ): void {
    const mcpFile = plugin.manifest.components.mcpServers;
    if (!mcpFile) return;
    const body = plugin.files.get(mcpFile);
    if (body === undefined) {
      warnings.push({
        pluginId: plugin.manifest.id,
        message: `mcpServers references missing file "${mcpFile}" — skipped`,
      });
      return;
    }
    files.push({
      pluginId: plugin.manifest.id,
      path: path.posix.join(".continue", "mcp", `${plugin.manifest.id}.json`),
      contents: body,
    });
    warnings.push({
      pluginId: plugin.manifest.id,
      message:
        "MCP server config exported to .continue/mcp/. Continue will NOT auto-register — review and merge into config.yaml's mcpServers section manually.",
    });
    if (!plugin.manifest.permissions.registerMcp) {
      warnings.push({
        pluginId: plugin.manifest.id,
        message:
          "Plugin declares mcpServers but does not request the `registerMcp` permission. Export emitted for reference only; do not configure.",
      });
    }
  }
}

function renderContinueReadme(plugins: LoadedPlugin[], hasConfig: boolean): string {
  const lines: string[] = [
    HEADER,
    "",
    "# Tierkit → Continue export",
    "",
    "Continue (v0.9+) loads a workspace assistant from `.continue/`. This directory was produced by `tierkit export continue`.",
    "",
    "## Layout",
    "",
    "- `config.yaml` — Continue assistant config. `models` is populated from `tierkit.config.json::modelProfiles`. API keys are referenced via `${{ secrets.YOUR_ENV_VAR }}` — set them in Continue's secrets UI.",
    "- `rules/` — Auto-loaded rules. Numeric prefix establishes load order:",
    "  - `00-` Permission contract — what each plugin may and may not do.",
    "  - `10-` Plugin rules.",
    "  - `20-` Modes translated to persona rules (Continue has no first-class custom modes).",
    "- `prompts/<plugin-id>-<command>.prompt` — Continue **does** register these as slash commands. After export, `/superpowers-free-brainstorm` becomes available in Continue's chat.",
    "- `mcp/<plugin-id>.json` — MCP server staging files. **Continue will not auto-register them.** Review and merge into `config.yaml::mcpServers` manually if you trust the source.",
    "",
  ];

  if (!hasConfig) {
    lines.push(
      "## ⚠️ No `tierkit.config.json` found",
      "",
      "Run `tierkit init` and add `modelProfiles` to populate the `models:` section of `config.yaml`. Until then, that section is empty and Continue will not have any models to use.",
      "",
    );
  }

  lines.push("## Installed plugins", "");
  if (plugins.length === 0) {
    lines.push("_(no plugins installed)_", "");
  } else {
    for (const p of plugins) {
      const m = p.manifest;
      const perms = listGrantedPermissions(m.permissions);
      const highRisk = listHighRiskGranted(m.permissions);
      lines.push(`### ${m.name} \`${m.id}@${m.version}\``);
      lines.push("");
      lines.push(m.description);
      lines.push("");
      lines.push(`- **freedom**: ${m.freedom.level}`);
      lines.push(
        `- **permissions**: ${perms.length === 0 ? "(none)" : perms.map((p) => `\`${p}\``).join(", ")}`,
      );
      if (highRisk.length > 0) {
        lines.push(
          `- **high-risk granted**: ${highRisk.map((p) => `\`${p}\``).join(", ")} — review before use`,
        );
      }
      lines.push("");
    }
  }

  lines.push(
    "## Re-export",
    "",
    "After updating a plugin source or `tierkit.config.json`, re-run `tierkit export continue` to regenerate this directory.",
    "",
    "## Older Continue versions",
    "",
    "Continue versions before workspace assistant support (~0.9.0) only honor `~/.continue/config.json`. On those versions, manually translate the contents of `config.yaml` into your global config and add the prompts in `~/.continue/prompts/`.",
    "",
  );

  return lines.join("\n");
}
