import { stringify as yamlStringify } from "yaml";
import type { TierkitConfig, ModelProfile, ModelTier } from "@tierkit/core";

/**
 * Build the JSON object that becomes `.continue/config.yaml`.
 *
 * Continue's role taxonomy (chat/edit/autocomplete/embed/rerank) and Tierkit's
 * role hints don't perfectly overlap. We project conservatively:
 *
 * - `local-device` tier  → roles include `chat`, `edit`, `autocomplete` (heavy local use is fine)
 * - `private-remote`     → roles include `chat`, `edit` (skip autocomplete to keep that low-latency local)
 * - `public-cloud`       → roles include `chat` ONLY (review-only stance — never wire into edit/autocomplete)
 *
 * Plugin authors override per-profile via the `roles` array on each model profile.
 */

export interface ContinueModelEntry {
  name: string;
  provider: string;
  model: string;
  apiBase?: string;
  apiKey?: string;
  roles: string[];
}

export interface ContinueConfig {
  name: string;
  version: string;
  schema: "v1";
  models: ContinueModelEntry[];
  rules?: string[];
  prompts?: string[];
}

export interface RenderConfigInput {
  /** Tierkit config — if omitted, models[] is empty and a TODO comment is added in the file. */
  config?: TierkitConfig;
}

export interface RenderConfigResult {
  yaml: string;
  warnings: { message: string }[];
}

export function renderContinueConfig(input: RenderConfigInput): RenderConfigResult {
  const warnings: { message: string }[] = [];
  const models: ContinueModelEntry[] = [];

  if (input.config) {
    for (const [id, profile] of Object.entries(input.config.modelProfiles)) {
      const entry = profileToContinueModel(id, profile, warnings);
      models.push(entry);
    }
  }

  const cfg: ContinueConfig = {
    name: "tierkit-export",
    version: "0.0.1",
    schema: "v1",
    models,
  };

  const header =
    `# Generated by Tierkit. Do not edit by hand — edit tierkit.config.json + plugins and re-export.\n` +
    `# Tierkit does NOT register MCP servers automatically. See ./TIERKIT.md and ./mcp/ for staging files.\n`;

  const todo =
    models.length === 0
      ? `\n# TODO: no model profiles found in tierkit.config.json. Add 'modelProfiles' there and re-export,\n# or fill in this 'models:' section manually.\n`
      : "";

  const yaml = header + todo + yamlStringify(cfg, { lineWidth: 120 });
  return { yaml, warnings };
}

function profileToContinueModel(
  id: string,
  profile: ModelProfile,
  warnings: { message: string }[],
): ContinueModelEntry {
  const provider = mapProvider(profile.provider, profile.kind);
  const roles = pickRoles(profile);

  const entry: ContinueModelEntry = {
    name: id,
    provider,
    model: profile.model,
    roles,
  };

  if (profile.baseUrl) entry.apiBase = profile.baseUrl;
  if (profile.apiKeyEnv) entry.apiKey = `\${{ secrets.${profile.apiKeyEnv} }}`;

  if (profile.kind === "public-cloud" && roles.some((r) => r !== "chat")) {
    warnings.push({
      message: `public-cloud profile "${id}" was forced to chat-only role for safety; Continue may not honor "${roles.filter((r) => r !== "chat").join(",")}" for review-only output.`,
    });
  }

  return entry;
}

function mapProvider(provider: string, kind: ModelTier): string {
  const p = provider.toLowerCase();
  if (p === "ollama") return "ollama";
  if (p === "anthropic") return "anthropic";
  if (p === "openai") return "openai";
  if (p === "openai-compatible") return "openai";
  if (p === "azure" || p === "azure-openai") return "azure";
  if (p === "groq") return "groq";
  if (p === "mistral") return "mistral";
  if (p === "google" || p === "gemini") return "gemini";
  if (kind === "local-device") return "ollama";
  return "openai";
}

function pickRoles(profile: ModelProfile): string[] {
  const explicit = profile.roles ?? [];
  if (explicit.length > 0) {
    const mapped = new Set<string>();
    for (const r of explicit) {
      const lr = r.toLowerCase();
      if (lr.includes("chat") || lr === "planner" || lr === "reviewer") mapped.add("chat");
      if (lr.includes("edit") || lr === "coder" || lr.includes("debug") || lr.includes("complex-coder")) mapped.add("edit");
      if (lr.includes("autocomplete") || lr === "simple-coder") mapped.add("autocomplete");
      if (lr.includes("embed")) mapped.add("embed");
      if (lr.includes("rerank")) mapped.add("rerank");
    }
    if (mapped.size === 0) mapped.add("chat");
    return roleFilterForTier(profile.kind, [...mapped]);
  }
  switch (profile.kind) {
    case "local-device":
      return ["chat", "edit", "autocomplete"];
    case "private-remote":
      return ["chat", "edit"];
    case "public-cloud":
      return ["chat"];
  }
}

function roleFilterForTier(kind: ModelTier, roles: string[]): string[] {
  if (kind === "public-cloud") return roles.filter((r) => r === "chat");
  if (kind === "private-remote") return roles.filter((r) => r !== "autocomplete");
  return roles;
}
