import path from "node:path";
import type { LoadedPlugin, PluginManifest, PermissionFlags } from "@tierkit/core";

const HEADER =
  "<!-- Generated by Tierkit. Do not edit by hand — edit the source plugin and re-export. -->";

export interface RenderedFile {
  pluginId: string;
  path: string;
  contents: string;
}

export interface RenderResult {
  files: RenderedFile[];
  warnings: { pluginId: string; message: string }[];
}

/**
 * Permission contract for Continue.
 *
 * Continue has rules (auto-loaded markdown) but no permission/group enforcement. The contract
 * mirrors the Cline approach: translate every Tierkit permission into a natural-language
 * MAY / MUST NOT line so the agent reads the contract before every action.
 */
export function renderPermissionContract(manifest: PluginManifest): RenderedFile {
  const p: PermissionFlags = manifest.permissions;
  const mustNot: string[] = [];
  const may: string[] = [];

  if (p.readFiles) may.push("Read files in the workspace.");
  else mustNot.push("Read files outside of what the user explicitly shares.");

  if (p.editFiles) may.push("Edit files in the workspace via Continue's edit/apply features.");
  else mustNot.push("Edit, create, or delete files in the workspace.");

  if (p.runCommands)
    may.push("Run shell commands — surface what will run and pause for approval first.");
  else mustNot.push("Run shell commands of any kind. Even read-only commands are out of scope for this plugin.");

  if (p.installDependencies) may.push("Install dependencies — explicit approval required.");
  else mustNot.push("Install, update, or remove dependencies.");

  if (p.modifyAgentSettings) may.push("Modify Continue settings — explicit approval required.");
  else mustNot.push("Modify Continue configuration, custom instructions, or MCP settings.");

  if (p.registerMcp)
    may.push("Suggest registering an MCP server — never silently auto-register; ask the user to add it in Continue MCP settings.");
  else mustNot.push("Register MCP servers. If MCP work appears necessary, stop and ask the user.");

  if (p.accessSecrets)
    may.push("Read secrets only when the task demonstrably needs them; redact before sending to remote tiers.");
  else mustNot.push("Access secrets, credentials, environment variables holding tokens, or `.env`-style files.");

  if (p.useNetwork) may.push("Make network requests when the task requires them.");
  else mustNot.push("Make outbound network requests.");

  if (p.usePublicCloudModel)
    may.push("Use a public-cloud model — only in review-only mode and only after the user explicitly approves the escalation.");
  else mustNot.push("Use public-cloud models. This plugin operates on local-device (and optionally private-remote) models only.");

  if (p.usePrivateRemoteModel)
    may.push("Use a private-remote model when the task exceeds local-device capacity.");

  const lines: string[] = [
    HEADER,
    "",
    `# Permission contract — ${manifest.name} (\`${manifest.id}\`)`,
    "",
    "_This file is auto-generated by Tierkit from the plugin's `permissions` block. Do not edit directly._",
    "",
    `Plugin **${manifest.id}** declared the following permission contract. The agent must follow it strictly while this plugin's context is loaded.`,
    "",
    "## You MAY",
    "",
  ];
  if (may.length === 0) lines.push("_(nothing — this plugin is read-only-passive)_", "");
  else {
    for (const item of may) lines.push(`- ${item}`);
    lines.push("");
  }

  lines.push("## You MUST NOT", "");
  if (mustNot.length === 0) lines.push("_(no explicit prohibitions)_", "");
  else {
    for (const item of mustNot) lines.push(`- ${item}`);
    lines.push("");
  }

  lines.push(
    "## Escalation",
    "",
    "- Public-cloud model output is **review-only** — it may suggest changes, but a local or private-remote model applies them after human review.",
    "- Before sending any context to a remote tier (private-remote or public-cloud), redact secrets, production URLs, and customer data.",
    "",
  );

  return {
    pluginId: manifest.id,
    path: `.continue/rules/00-${manifest.id}-permission.md`,
    contents: lines.join("\n"),
  };
}

export function renderPluginRules(plugin: LoadedPlugin): RenderResult {
  const id = plugin.manifest.id;
  const files: RenderedFile[] = [];
  const warnings: RenderResult["warnings"] = [];

  for (const rel of plugin.manifest.components.rules) {
    const body = plugin.files.get(rel);
    if (body === undefined) {
      warnings.push({ pluginId: id, message: `rule references missing file "${rel}" — skipped` });
      continue;
    }
    const slug = slugify(path.basename(rel, path.extname(rel)));
    files.push({
      pluginId: id,
      path: `.continue/rules/10-${id}-rule-${slug}.md`,
      contents: `${HEADER}\n\n${body.trim()}\n`,
    });
  }

  return { files, warnings };
}

export function renderPluginModes(plugin: LoadedPlugin): RenderResult {
  const id = plugin.manifest.id;
  const files: RenderedFile[] = [];
  const warnings: RenderResult["warnings"] = [];

  for (const mode of plugin.manifest.components.modes) {
    const body = plugin.files.get(mode.file);
    if (body === undefined) {
      warnings.push({
        pluginId: id,
        message: `mode "${mode.id}" references missing file "${mode.file}" — skipped`,
      });
      continue;
    }
    const lines = [
      HEADER,
      "",
      `# Persona: ${mode.name}`,
      "",
      `_(from plugin \`${id}\`, mode id \`${mode.id}\`, role \`${mode.role}\`. Continue has no first-class custom modes — when the user asks the agent to adopt this persona, follow the body below.)_`,
      "",
      `**Declared tools:** ${mode.tools.length === 0 ? "(none)" : mode.tools.map((t) => `\`${t}\``).join(", ")}. These are *intentions*, not capabilities — the permission contract for this plugin still wins.`,
      "",
      body.trim(),
      "",
    ];
    files.push({
      pluginId: id,
      path: `.continue/rules/20-${id}-mode-${slugify(mode.id)}.md`,
      contents: lines.join("\n"),
    });
  }

  return { files, warnings };
}

/**
 * Continue prompt templates ARE first-class slash commands (one of the few things Continue
 * registers natively). File format: YAML frontmatter (name + description) + body, with `.prompt`
 * extension so Continue picks it up.
 */
export function renderPluginPrompts(plugin: LoadedPlugin): RenderResult {
  const id = plugin.manifest.id;
  const files: RenderedFile[] = [];
  const warnings: RenderResult["warnings"] = [];

  for (const cmd of plugin.manifest.components.commands) {
    const body = plugin.files.get(cmd.file);
    if (body === undefined) {
      warnings.push({
        pluginId: id,
        message: `command "${cmd.name}" references missing file "${cmd.file}" — skipped`,
      });
      continue;
    }
    const slashName = `${id}-${cmd.name}`;
    const lines = [
      "---",
      `name: ${slashName}`,
      `description: ${jsonish(cmd.description)}`,
      "---",
      "",
      HEADER,
      "",
      body.trim(),
      "",
    ];
    files.push({
      pluginId: id,
      path: `.continue/prompts/${slashName}.prompt`,
      contents: lines.join("\n"),
    });
  }

  return { files, warnings };
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

function jsonish(s: string): string {
  if (/[":#\n]/.test(s)) return JSON.stringify(s);
  return s;
}
